# Конфигурация PHPLint
version: 2

# Папки и файлы для исключения из проверки
excluded_dirs:
  - vendor
  - node_modules
  - storage
  - resources

excluded_files:
  - .env

# Расширения файлов, которые следует проверять
extensions:
  - php

# Параметры запуска
jobs: 10 # Количество параллельных задач для выполнения
path: . # Путь к директории для анализа
